Lora1
Dani-gr/MIAU pull request #12
Opened 2023-04-13 15:50 UTC by LoraShk1

Added animal and number game

2023-04-13 16:36 UTC, Dani-gr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Practice mode, two games (for now, copying the other game, maybe creating another)](https://trello.com/c/qYvWry5m/11-practice-mode-two-games-for-now-copying-the-other-game-maybe-creating-another)

2023-04-13 16:48 UTC, Dani-gr commented on ClientApp/practiceactivity2.html
We should change the alt text of Umberto.

2023-04-13 16:49 UTC, Dani-gr commented on ClientApp/practiceactivity3.html
Same here, we should change the alt text of Umberto.

2023-04-13 17:23 UTC, Dani-gr requested changes
It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).

2023-04-13 17:23 UTC, Dani-gr commented on ClientApp/js/colorGame.js
Los cambios de este archivo son accidentales, no deberían realizarse.

2023-04-13 17:26 UTC, xmariafdz commented
Games work properly, but main menu's buttons are broken

2023-04-13 19:16 UTC, LoraShk1 commented on ClientApp/practiceactivity2.html
The umberto img is just a placeholder honestly because it gets exchaged with another image immediatly... So i dont know if its that important

2023-04-13 19:17 UTC, LoraShk1 commented
> It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).

I think i fixed the issue with your game in the last commit

2023-04-13 19:20 UTC, LoraShk1 commented
> main menu's buttons are broken :(

you mean not linking to the right target or design is broken? because the design is not fully finished i think

2023-04-13 19:20 UTC, LoraShk1 commented
> main menu's buttons are broken :(

you mean not linking to the right target or design is broken? because the design is not fully finished i think

2023-04-13 21:43 UTC, Dani-gr commented on ClientApp/practiceactivity2.html
Oh, okey then

2023-04-13 21:45 UTC, Dani-gr commented
> > It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).
> 
> I think i fixed the issue with your game in the last commit

Hmm, I still see it the same way, did you push the commit?

2023-04-13 22:29 UTC, LoraShk1 commented
> > > It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).
> > 
> > 
> > I think i fixed the issue with your game in the last commit
> 
> Hmm, I still see it the same way, did you push the commit?

what exactly is not working because for me the games work

2023-04-13 22:33 UTC, Dani-gr commented
> > > > It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).
> > > 
> > > 
> > > I think i fixed the issue with your game in the last commit
> > 
> > 
> > Hmm, I still see it the same way, did you push the commit?
> 
> what exactly is not working because for me the games work

The color game doesn't work (there aren't any spaces), since all the uses of the variable `color` have been changed to `number`. If it works for you, check if the commit hasn't been pushed yet

2023-04-13 22:35 UTC, LoraShk1 commented
> > > > > It works well, but the menu is messed up (maybe related to commonStyles?), and my game doesn't work (just reverting those changes should be fine).
> > > > 
> > > > 
> > > > I think i fixed the issue with your game in the last commit
> > > 
> > > 
> > > Hmm, I still see it the same way, did you push the commit?
> > 
> > 
> > what exactly is not working because for me the games work
> 
> The color game doesn't work (there aren't any spaces), since all the uses of the variable `color` have been changed to `number`. If it works for you, check if the commit hasn't been pushed yet

i did - thats exactly what i fixed. I commited again maybe its better now ?

2023-04-13 22:41 UTC, Dani-gr commented
It still doesn't work for me, I'll try to revert the changes on that file
![image](https://user-images.githubusercontent.com/100536136/231898331-a3db9ef4-2f29-4604-9fe1-531ddfd7da6f.png)

2023-04-13 22:51 UTC, Dani-gr approved these changes
Now it works for me, lmk if it does for you too

2023-04-14 22:59 UTC, xmariafdz commented
both games work for me! Have the same issue with the menu, but we can fix it later

2023-04-14 23:00 UTC, xmariafdz approved these changes

2023-04-14 23:07 UTC, Nu36 approved these changes

2023-04-15 00:11 UTC, Dani-gr commented
Since it seems ok, I'll proceed with the merge.

2023-04-15 00:11 UTC, merged