made main menu responsive
Dani-gr/MIAU pull request #20
Opened 2023-04-26 20:56 UTC by LoraShk1

2023-04-27 11:35 UTC, Nu36 approved these changes
It works well for me

Be careful when doing the merge because you have old files that are changed on main!

2023-04-27 12:47 UTC, Dani-gr requested changes
We agreed on having most styles (if not all possible) outside the html (having them all on the css), so if you could refactor them it'd be perfect. I see it pretty well, although I have to fullscreen the page. Moreover, when shrinking the page horizontally, the text looks bad; I think it should be fixed by setting a min-width to the cards.

A minor detail I've also noticed is that the href to the "shop" leads to the studymode, it should be either "customizeUmberto.html" or empty 'till we have it finished (if at all).

2023-05-02 13:43 UTC, xmariafdz approved these changes

2023-05-02 13:55 UTC, Dani-gr approved these changes
Perfect!

2023-05-03 07:01 UTC, merged